name: Latest Tag

on:
  release:
    types:
      - released
  push:
    tags:
      - "v?[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
